# Generated by Django 3.0.7 on 2020-10-23 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flashcard',
            old_name='Anverse',
            new_name='anverse',
        ),
        migrations.RenameField(
            model_name='flashcard',
            old_name='Reverse',
            new_name='reverse',
        ),
    ]
